
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: platform
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Project for k8s platform apps.
  sourceRepos:
  - '*'
  destinations:
  - namespace: '*'
    server: '*'
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'

---

apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: datasources
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Project for k8s datasources apps.
  sourceRepos:
  - '*'
  destinations:
  - namespace: '*'
    server: '*'
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'

---

apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: microservices
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Project for k8s microservices apps.
  sourceRepos:
  - '*'
  destinations:
  - namespace: '*'
    server: '*'
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'

---

apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: integrated-tools
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Project for k8s integrated-tools apps.
  sourceRepos:
  - '*'
  destinations:
  - namespace: '*'
    server: '*'
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'

---

apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: client-tools
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Project for k8s client-tools apps.
  sourceRepos:
  - '*'
  destinations:
  - namespace: '*'
    server: '*'
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'

{{- if .Values.deployment.saas.enabled }}
---

apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: saas-tools
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Project for saas client-tools apps.
  sourceRepos:
  - '*'
  destinations:
  - namespace: '*'
    server: '*'
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
{{- end }}
