{{- if .Values.deployment.saas.enabled }}
# GitHub PAT for repo Contents read-only access
apiVersion: v1
kind: Secret
metadata:
  name: repo-openframe-saas
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: "{{ $.Values.deployment.saas.repository.URL }}"
  username: read-contents
  password: "{{ $.Values.deployment.saas.repository.password }}"
type: Opaque
{{- end }}
