apiVersion: v1
kind: ConfigMap
metadata:
  name: openframe-config
  labels:
    app: openframe-config
data:
  SPRING_PROFILES_ACTIVE: "k8s"

  # OSS Environment Variables
  CONFIG_GIT_REPO_0: "{{ .Values.deployment.oss.config.repoName }}"
  CONFIG_GIT_BRANCH_0: "{{ .Values.deployment.oss.config.branch }}"

  # Additional SaaS Environment Variables
  {{- if .Values.deployment.saas.enabled }}
  CONFIG_GIT_REPO_1: "{{ .Values.deployment.saas.config.repoName }}"
  CONFIG_GIT_BRANCH_1: "{{ .Values.deployment.saas.config.branch }}"
  GITHUB_PASSWORD: "{{ .Values.deployment.saas.config.password }}"
  {{- end }}