registerJob:
  enabled: true
servicemonitor:
  enabled: true



pinot:
  cluster:
    name: pinot 
  server:
    replicaCount: 2
  
  controller:
    external:
      enabled: false
  broker:
    external:
      enabled: false