registerJob:
  enabled: true
servicemonitor:
  enabled: true



pinot:
  cluster:
    name: pinot 
  server:
    replicaCount: 2
  
  controller:
    service:
      external:
        enabled: false
  broker:
    service:
      external:
        enabled: false